/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ndbghtqcqtnqcqtxnfym"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kYmdodHFjcXRucWNxdHhuZnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzMzM4ODAsImV4cCI6MjA5MDkwOTg4MH0.C5FYdof6IpzL8Nkr-YPrFtBNOoEtNPEfMFNsEXl-k_M"